- R/plot_cme.R
The default y-axis labels in average/conditional marginal effect plots reads as "Marginal effect of _condition_variable_". I think this is meant to be "Marginal effect of _effect_variable_" instead.
> changes condition to effect in y-axis labels

- vignettes/stata.Rmd
Here is a first attempt at creating a vignette comparing Stata's margins command and the functions of marginaleffects. I was inspired by these two issues:
https://github.com/vincentarelbundock/marginaleffects/issues/226
https://github.com/strengejacke/ggeffects/issues/249
And the margins' documentation here:
https://thomasleeper.com/margins/articles/Stata.html
> Add Stata vignette

- R/comparisons.R
- R/sanitize_transform_pre.R
- vignettes/transformation.Rmd
> Add "lnoravg" (log of marginal odds ratio) an built-in option to transform_pre in comparisons()

- vignettes/transformation.Rmd
Added a demonstration of working with `transform_pre` and `transform_post` with hurdle lognormal models (following https://github.com/vincentarelbundock/marginaleffects/issues/343#issuecomment-1135986525)
> Add example of back transforming lognormal results

- R/get_vcov.R
- R/methods_fixest.R
- inst/tinytest/test-pkg-fixest.R
Following #485, here's an attempt to avoid using `do.call`s with `fixest`. Basically replacing the do.call with the explicit list of arguments, minus the `level` one in the second `do.call`. Not sure whether this is what you were thinking @vincentarelbundock. Tested with the workflow mentioned [here](https://github.com/vincentarelbundock/marginaleffects/issues/485#issuecomment-1245327633), returning:
```r
test-pkg-fixest.R.............    0 tests    0.3s [Exited at #3: problems testing fixest because of `get_data` from environment]
All ok, 0 results (0.3s)
```
Tested with the `N = 1e6` and it is indeed way faster.
> Explicit predict instead of do.call

- R/comparisons.R
Hello Vincent,
`do.call()` + `paste()` is generally faster than `apply()` + `paste()` (that is used in `comparisons()`). It only creates a marginal gain but better than nothing. I used some of the benchmarks of the [vignette on performance](https://vincentarelbundock.github.io/marginaleffects/articles/performance.html). 
``` r
N <- 1e5
dat <- data.frame(matrix(rnorm(N * 26), ncol = 26))
mod <- lm(X1 ~ ., dat)
bench::mark(
marginaleffects(mod, vcov = FALSE, variables = "X3"),
marginaleffects(mod, variables = "X3"),
iterations = 10,
check = FALSE
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression                                                min   median itr/s…¹
#>   <bch:expr> …
```
> Small speedup

- README.md
- vignettes/toc_external.Rmd
This is just a simple fix to the README file to update the link for my Bayesian Model Averaged Marginal Effects blog post.
> Fixing the Bayesian Model Averaging Link in README

- vignettes/marginaleffects.Rmd
Link to `modelsummary` instead of `marginaleffects` in "Get started" page
> Correct link for `modelsummary`

- DESCRIPTION
- NEWS.md
- R/get_predict.R
Two things:
1. Creating a `data.table()` takes some time and is not necessary in `get_predict()` because there’s no `data.table`-specific operations. It is faster to create a list, which is also accepted by `setDF()`. 
2. If I'm not mistaken, the only reason why you use `as.numeric(pred)` is because of `svyglm` which returns an object of class `svystat`. It's faster to directly assign the class "numeric" when there are a lot of observations.
These improve the performance mostly when `vcov = TRUE`.
I use the same setup as in the [performance vignette](https://vincentarelbundock.github.io/marginaleffects/articles/performance.html) but with less observations because it takes quite some time to run all these benchmarks.
``` r
N <- 3*1e4
dat <- …
```
> Improve the performance of `get_predict()`

- DESCRIPTION
- NEWS.md
- R/datagrid.R
Benchmark:
``` r
tmp <- list()
for (i in 1:30000) {
tmp[[i]] <- mtcars
}
tmp2 <- data.table::rbindlist(tmp)
tmp2$am <- as.logical(tmp2$am)
dim(tmp2)
#> [1] 960000     11
mod <- lm(mpg ~ hp + factor(cyl), data = tmp2)
```
Old:
```r
bench::mark(
predictions(mod, variables = list(hp = c(100, 120))),
predictions(mod, newdata = datagridcf(hp = c(100, 120), cyl = c(4, 6))),
check = FALSE
)
#> disabled.
#> # A tibble: 2 × 6
#>   expression                                                                 min
#>   <bch:expr>                                                              <bch:>
#> 1 predictions(mod, variables = list(hp = c(100, 120)))                     12.4s
#> 2 predictions(mod, …
```
> Improve speed of `predictions()`

- R/get_contrast_data.R
- R/get_contrasts.R
Before:
``` r
tmp <- list()
for (i in 1:30000) {
tmp[[i]] <- mtcars
}
tmp2 <- data.table::rbindlist(tmp)
mod <- lm(mpg ~ hp + disp + cyl, data = tmp2)
results <- bench::mark(
out = comparisons(mod, variables = list(hp = c(100, 120), cyl = c(4, 6))),
iterations = 10
)
#> disabled.
results[, c(1, 3, 5)]
#> # A tibble: 1 × 3
#>   expression   median mem_alloc
#>   <bch:expr> <bch:tm> <bch:byt>
#> 1 out           9.68s    7.29GB
```
After:
``` r
results <- bench::mark(
out = comparisons(mod, variables = list(hp = c(100, 120), cyl = c(4, 6))),
iterations = 10
)
#> disabled.
results[, c(1, 3, 5)]
#> # A tibble: 1 × 3
#> …
```
> Misc perf improvements

- R/comparisons.R
- R/sanitize_type.R
Before:
``` r
N <- 3*1e4
dat <- data.frame(matrix(rnorm(N * 26), ncol = 26))
mod <- lm(X1 ~ ., dat)
bench::mark(
slopes(mod),
iterations = 10
)
#> disabled.
#> # A tibble: 1 × 6
#>   expression       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 slopes(mod)    17.5s    20.5s    0.0506    23.4GB     1.33
```
After:
``` r
bench::mark(
slopes(mod),
iterations = 10
)
#> disabled.
#> # A tibble: 1 × 6
#>   expression       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 slopes(mod)    16.4s …
```
> Small speed improvement

- R/get_contrasts.R
_marginaleffects_ depends on R > 3.5, so `|>` does not work.
> Don't use R 4.0 pipe in code

- R/predictions.R
Example from [this vignette](https://vincentarelbundock.github.io/marginaleffects/articles/predictions.html#multinomial-models).
Before:
``` r
library(nnet)
mtcars$gear <- factor(mtcars$gear)
tmp <- list()
for (i in 1:10000) tmp[[i]] <- mtcars
dat <- data.table::rbindlist(tmp)
nom <- multinom(gear ~ mpg + am * vs, data = dat, trace = FALSE)
bench::mark(
predictions(nom, type = "probs"),
iterations = 10
)
#> disabled.
#> # A tibble: 1 × 6
#>   expression                            min   median `itr/sec` mem_alloc gc/se…¹
#>   <bch:expr>                       <bch:tm> <bch:tm>     <dbl> <bch:byt>   <dbl>
#> 1 predictions(nom, type = "probs")      23s    26.5s    0.0384    3.96GB    1.01
#> # … …
```
> Speed gain in `predictions()` 

- NEWS.md
- R/imputation.R
- vignettes/multiple_imputation.Rmd
See commit messages for further details. This follows on issue  #739 
Two commits:
1. Return pooled model in `attr(mfx, "model")` after multiple imputation. This means that other tools such as `modelsummary` will find the appropriate summary statistics for the pooled model which it shows the values for.
2.  Modify multiple imputation vignette to try and clarify the generality of the use of the alternate slightly more manual workflow.
> Multiple Imputation Modifications: Return pooled model + improve documentation

- DESCRIPTION
- NEWS.md
- R/bootstrap_boot.R
- R/bootstrap_rsample.R
- inst/tinytest/test-inferences.R
Related to #761. The bootstrap is slow because it calls `get_modeldata()` a lot inside `predictions()`, which is `FUN` in these lines:
https://github.com/vincentarelbundock/marginaleffects/blob/274d9195ecc48a3430de76562187c0ddbe89687c/R/bootstrap_rsample.R#L34-L44 
What I'm thinking is that you already know the model data, it's the line `modcall[["data"]] <- data`. So you could pass this data directly to `predictions()` and avoid running `get_modeldata()`. 
This leads to very large performance gains:
``` r
library(dplyr, warn.conflicts = FALSE)
set.seed(1234)
big_mtcars <- mtcars %>% 
sample_n(15000, replace = TRUE)
mod <- lm(mpg ~ .,data=big_mtcars)
foo <- avg_predictions(mod) 
bench::mark(
test = inferences(foo, method="rsample", R = 30)
)
#> Warning: Recommend …
```
> Large speed improvement for `inferences()`

- vignettes/comparisons.Rmd
How vectors of length 1 differ from those of length >1 is fairly well-described in the function reference but was somewhat unclear in the vignette. I clarify here since it can be easy to miss otherwise.
> Update vignette to explicate how comparison functions treat vectors of length 1 versus >1

- NEWS.md
- R/get_contrasts.R
It's a bit more efficient to split a data.table and then call a specific element in the loop rather than filtering the whole data.table at each iteration.
Most of the improvement comes from the change to `merge()`, but I really can't tell why it's more efficient, it just seems to be.
(I changed a bit my way of benchmarking, now all results are in the table at the end)
```r
library(bench)
out <- cross::run(
pkgs = c("vincentarelbundock/marginaleffects", 
"etiennebacher/marginaleffects@speedup-elasticities"),
~ {
N <- 30000
dat <- data.frame(matrix(rnorm(N * 24), ncol = 24))
mod <- lm(X1 ~ ., dat)
bench::mark(
avg_slopes(mod, slope = "eydx"), 
avg_slopes(mod, slope = "dydx"), 
avg_slopes(mod, slope = "eyex"), 
check = FALSE,
iterations = 10
)
}
)
tidyr::unnest(out, …
```
> Performance improvement for elasticities

- R/type_dictionary.R
- inst/tinytest/test-pkg-mvgam.R
This PR adds additional supported prediction types for models of class `mvgam`. It also implements a few basic unit tests for these models
> Additional prediction types and tests for {mvgam}

- DESCRIPTION
- NEWS.md
- R/methods_survey.R
- inst/tinytest/test-pkg-survey.R
> issue `get_predict.svyglm()` throws "NAs introduced by coercion" when data row names are not integers #1131

- R/complete_levels.R
- R/datagrid.R
- R/get_se_delta.R
- R/get_term_labels.R
- R/methods_aod.R
- R/methods_brms.R
- R/methods_crch.R
- R/methods_gamlss.R
- R/methods_glmmTMB.R
- R/methods_nnet.R
- R/methods_ordinal.R
- R/sanity_model.R
Hi @vincentarelbundock, I've made a new package to find lints and automatically fix them ([`flint`](https://flint.etiennebacher.com/)). I used `marginaleffects` as one of my test cases and found a few lints so I thought you might want to remove them. In particular, I think it might have fixed a bug in `R/methods_nnet.R`.
FYI those fixes were automatically generated with `flint::fix_dir("R", exclude_linters = "equal_assignment")`. End of the self-advertising :)
> Fix some lints

- R/ci.R
- R/comparisons.R
- R/deprecated.R
- R/equivalence.R
- R/get_contrast_data_character.R
- R/get_contrast_data_factor.R
- R/get_contrast_data_numeric.R
- R/get_contrasts.R
- R/get_hypothesis.R
- R/hypotheses.R
- R/hypothesis_helper.R
- R/methods_quantreg.R
- R/plot_build.R
- R/sanitize_condition.R
- R/sanitize_numderiv.R
- R/sanitize_variables.R
Hi @vincentarelbundock, I've added [more linting rules](https://github.com/etiennebacher/flint/releases/tag/v0.0.2) in `flint` and here are a few additional fixes. Most of them are replacing `any(!expr)` by `!all(expr)` and adding `0` in front of the decimal when it's missing.
I'm testing on this package so for me there's no cost in proposing those changes, but of course let me know if you'd prefer not having this kind of PR.
> Fix more lints

- DESCRIPTION
- NEWS.md
- R/hypotheses.R
- inst/tinytest/helpers.R
- inst/tinytest/test-pkg-glmmTMB.R
This is a follow-up to #1224 
This is the full traceback that I get when calling `hypotheses(m, "b1 = b2")`, as shown in the minimum reproducible example in the original issue.
```
9. do.call("FUN", args) at get_se_delta.R#102
8. func(x) at get_jacobian.R#29
7. (function (func, x, eps = NULL)
{
baseline <- func(x)
inner_loop <- function(chunk, ...) { ...
}
6. do.call(get_jacobian_fdforward, numderiv) at get_jacobian.R#11
5. get_jacobian(func = function (x)
{
names(x) <- names(coefs)
model_tmp <- set_coef(model, x, ...) ...
}
4. do.call("get_jacobian", args) at get_se_delta.R#112
3. get_se_delta(model = structure(list(obj = list(par = c(beta = 1, beta = 1, beta = 1, beta = 1, betadisp = 0, theta = 0), fn = function (x = last.par[lfixed()],
...
}
2. do.call("get_se_delta", args) at …
```
> add ellipsis to FUNouter

- .github/scripts/benchmarks.R
- .github/workflows/benchmarks.yaml
Gives this (with only 10 and 50 obs):
> CI benchmark: produce table instead of plot

- DESCRIPTION
- NEWS.md
- R/comparisons.R
- R/predictions.R
Fixes #1295.
Old behaviour:
``` r
options(marginaleffects_lean = TRUE)
mod = lm(Sepal.Length ~ Petal.Length * Species, data = iris)
slopes(mod, variable = "Petal.Length", by = "Species")
#> 
#>  Estimate Std. Error     z Pr(>|z|)    S    CI low CI high
#>     0.542     0.2768  1.96   0.0501  4.3 -0.000165    1.08
#>     0.828     0.1023  8.10   <0.001 50.7  0.627824    1.03
#>     0.996     0.0871 11.43   <0.001 98.2  0.825054    1.17
#> 
#> Term: Petal.Length
#> Comparison: mean(dY/dX)
#> Columns: term, contrast, Species, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted
```
New behaviour:
``` r
options(marginaleffects_lean = TRUE)
mod = lm(Sepal.Length ~ Petal.Length * Species, data = iris)
slopes(mod, variable = "Petal.Length", …
```
> Retain "by" and "conf_level" attributes for lean objects

- R/utils.R
Observed in data.table's revdeps checker logs:
```
It is safer and faster to convert such variables to factor before fitting the model and calling a `marginaleffects` function.This warning appears once per session.
```
Note that `warning()` concatenates its inputs with `''`:
```r
warning(letters)
```
I'm not familiar with how `insight::format_warning()` handles vectors, so I opted to just build the string directly.
> Better concatenation of warning message

- R/bootstrap_boot.R
Caught with `flint`. I don't know if this is gonna have a meaningful impact but always nice to get those low-hanging fruits I think:
``` r
mat <- matrix(
sample(c(1:100, NA), 1e7, replace = TRUE), 
nrow = 500
)
bench::mark(
apply(mat, 2, mean, na.rm = TRUE),
colMeans(mat, na.rm = TRUE)
)
#> disabled.
#> # A tibble: 2 × 6
#>   expression                           min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 apply(mat, 2, mean, na.rm = TR… 237.74ms 269.86ms      3.71     312MB     22.2
#> 2 colMeans(mat, na.rm = TRUE)       7.37ms   7.41ms    135.       181KB      0
```
---
Edit: CI failures also occur on `main`
> Minor performance improvement in `bootstrap_boot()`

- R/comparisons.R
- R/datagrid.R
- R/methods_gamlss.R
- R/methods_mlr3.R
- R/print.R
- R/sanitize_condition.R
- R/sanitize_numderiv.R
- R/sanitize_reserved.R
- R/sanitize_variables.R
- R/sanity_by.R
- R/sanity_dots.R
- R/sanity_model.R
- R/utils.R
I improved the printing when the output is split due to too many rows. Previously, the top and bottom wouldn't necessarily be aligned. Now they are. I also did some minor code cleaning (mostly replacing `paste(., collapse = ", ")` with the cleaner but equivalent `toString(.)`).
> Improved printing when output is split

- NEWS.md
- R/comparisons.R
- R/predictions.R
- R/slopes.R
```r
pkgload::load_all()
mod <- lm(mpg ~ hp, mtcars)
p1 = predictions(mod, vcov = "rsample")
p2 = predictions(mod, vcov = "fwb")
p1 = avg_comparisons(mod, vcov = "rsample")
p1 = avg_comparisons(mod, vcov = "simulation")
p2 = avg_comparisons(mod, vcov = "fwb")
```
> `vcov=` accepts `inferences()` methods

- DESCRIPTION
- NEWS.md
- R/inferences.R
- R/inferences_boot.R
- R/inferences_fwb.R
- R/inferences_rsample.R
- R/inferences_simulation.R
- man/inferences.Rd
Updating for new version of `fwb`. Fixed issue where dots were not passed to `fwb()`. Added p-values to fwb, as these are now produced by `summary.fwb()` by inverting CIs. Added `conf_type` to simulation, allowing for Wald inference (including p-values); default perc is unchanged. Minor cleaning here and there to improve organization.
> Fixes to inferences()
